spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_trainer
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: personaltrainer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
